### ISSUE TITLE
retrieveServices方法适配原版

### ISSUE THREAD

**Issue by myl0204** [react-native-oh-library/react-native-ble-manager#17]
目前的实现，我们在使用中遇到2个问题。
1. 该方法的第二个参数`serviceUUIDs`在harmony中是必传的，否则会拿不到任何数据([具体实现](https://github.com/react-native-oh-library/react-native-ble-manager/blob/sig/harmony/ble_manager/src/main/ets/BleTurboModule.ts#L414))，而在[原库](https://github.com/react-native-oh-library/react-native-ble-manager/blob/sig/src/index.ts#L159)中是可选参数

2. 返回的`characteristics`数据中，缺少`properties`字段
[类型标注](https://github.com/react-native-oh-library/react-native-ble-manager/blob/sig/src/types.ts#L234C18-L234C32)

**Comment by Qy742698** [comment]
@myl0204  
1.retrieveServices这个方法在原库中并没有说明是可选参数；
2.上述问题二是在哪里使用到

**Comment by myl0204** [comment]
@Qy742698 

1. 原库的注释：* @param serviceUUIDs [iOS only] optional filter of services to retrieve. 提到了**optional filter**；
同时原库的方法定义也给了默认值（空数组）
```ts
  retrieveServices(peripheralId: string, serviceUUIDs: string[] = []) {}
``` 
原库iOS的代码中也对该参数做了判断
```swift
            var uuids: [CBUUID] = []
            for string in services {
                let uuid = CBUUID(string: string)
                uuids.append(uuid)
            }
            
            if !uuids.isEmpty {
                peripheral.instance.discoverServices(uuids)
            } else {
                peripheral.instance.discoverServices(nil)
            }
```
2. 我们需要读取property中的`write`属性 来判断是否向其写入特征值

**Comment by Qy742698** [comment]
@myl0204  
1.需要在此harmony方法里面加一个判断uuids是否为空就可以使用，
2.对于问题二需要一段时间才能实现，实现好后发布新版本

**Comment by Qy742698** [comment]
@myl0204 
 请问你是在使用retrieveServices这个份方法的时候是需要用到property中的write属性来判断是否向其写入特征值吗，还是其他的方法

**Comment by myl0204** [comment]
@Qy742698 
是的，通过`retrieveServices`方法拿到各种特征值，然后找到`write: true`的特征值，对其进行写入操作。

**Comment by Qy742698** [comment]
@myl0204  Do you need to return all the properties in property?

**Comment by myl0204** [comment]
@Qy742698  In this case we only need the property _write_.

**Comment by Qy742698** [comment]
@myl0204  好的
