### ISSUE TITLE
如何自行打包？

### ISSUE THREAD

**Issue by myl0204** [react-native-oh-library/react-native-ble-manager#24]
这个库我们在使用的过程中还遇到些其他问题，现在我们希望在现有代码上进行修改，然后自行打包。

从修改代码到最后的tgz包，需要做哪些操作？

我目前简化后的步骤是
1. 改代码
2. 打har包、替换
3. npm pack打tgz包

但是打出来的包没法用，请教下是少了什么步骤

**Comment by Qy742698** [comment]
Which side of the code did you change?

**Comment by myl0204** [comment]
harmony/ble_manager/src/main/ets/*

@Qy742698

**Comment by Qy742698** [comment]
Where did you pack the third step?

**Comment by myl0204** [comment]
root folder

**Comment by Qy742698** [comment]
Packaging must be performed in the root directory of the original database.

**Comment by myl0204** [comment]
I did that. And I got a file named "react-native-oh-tpl-react-native-ble-manager-11.5.2-0.0.4"

**Comment by Qy742698** [comment]
Here are the steps. See where you have a problem with the process.

**Comment by myl0204** [comment]
Where are the steps? I can't see anything 👀
